### ISSUE TITLE
`adlimidi <midifile> -reverb none` crash

### ISSUE THREAD

**Issue by fenugrec** [bisqwit/adlmidi#14]
```
ADLMIDI: MIDI (etc.) player with OPL3 emulation.............
(C) -- http://iki.fi/bisqwit/source/adlmidi.html............/usr/include/c++/13.2.1/string_view:258: constexpr const std::basic_string_view<_CharT, _Traits>::value_type& std::basic_string_view<_CharT, _Traits>::operator[](size_type) const [with _CharT = char; _Traits = std::char_traits<char>; const_reference = cons
Program received signal SIGABRT, Aborted.
0x00007ffff78b932c in ?? () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff78b932c in ?? () from /usr/lib/libc.so.6
#1  0x00007ffff78686c8 in raise () from /usr/lib/libc.so.6
#2  0x00007ffff78504b8 in abort () from /usr/lib/libc.so.6
#3  0x00007ffff7bfe3b2 in std::__glibcxx_assert_fail (file=file@entry=0x555555578900 "/usr/include/c++/13.2.1/string_view",
    line=line@entry=0x102,
    function=function@entry=0x555555578800 "constexpr const std::basic_string_view<_CharT, _Traits>::value_type& std::basic_string_view<_CharT, _Traits>::operator[](size_type) const [with _CharT = char; _Traits = std::char_traits<char>; const_r"...,
    condition=condition@entry=0x555555578033 "__pos < this->_M_len") at /usr/src/debug/gcc/gcc/libstdc++-v3/src/c++11/debug.cc:61
#4  0x00005555555596c0 in std::basic_string_view<char, std::char_traits<char> >::operator[] (this=<synthetic pointer>,
    __pos=<optimized out>) at /usr/include/c++/13.2.1/string_view:256
#5  std::basic_string_view<char, std::char_traits<char> >::operator[] (__pos=<optimized out>, this=<synthetic pointer>)
    at /usr/include/c++/13.2.1/string_view:256
#6  ParseReverb (specs=...) at src/midiplay.cc:2525
#7  0x000055555555885a in main (argc=0x4, argv=0x7fffffffe018) at src/midiplay.cc:3248
```

(adlmidi compiled as of eded08f549561d08bbaadea29800819c7c6cfacf )

**Comment by bisqwit** [comment]
Unable to confirm, but should be fixed in 944a3e70d60dd7554cde94675f71ab7c0a4ffaa2.
